server:
  port: 9527

spring:
  application:
    name: cloud-gateway #以微服务注册进consul或nacos服务列表内
  cloud:
    consul: #配置consul地址
      host: localhost
      port: 8500
      discovery:
        prefer-ip-address: true
        service-name: ${spring.application.name}
    gateway:
      routes:
        - id: pay_routh1 #pay_routh1                #路由的ID(类似mysql主键ID)，没有固定规则但要求唯一，建议配合服务名
          #uri: http://localhost:8001                #匹配后提供服务的路由地址
          uri: lb://cloud-payment-service          #匹配后提供服务的路由地址

          predicates:
            - Path=/pay/gateway/get/**              # 断言，路径相匹配的进行路由
            #################常用断言api #####################################################
            #- After=2024-05-15T15:40:10.417185900+08:00[Asia/Shanghai]  #在什么时间之后可以访问
            #- Before=2024-05-15T15:41:10.417185900+08:00[Asia/Shanghai]  #在什么时间之前可以访问
            #- Between=2024-05-15T15:41:10.417185900+08:00[Asia/Shanghai],2024-05-15T15:45:10.417185900+08:00[Asia/Shanghai]  #在某个时间段内可以访问
            #- Cookie=username,feiyun  #含cookie且cookie name为feiyun才能访问
            #- Header=X-Request-Id, \d+  #请求头要有X-Request-Id属性并且值为整数的正则表达式
            #- Host=**.atguigu.com #  Host Route Predicate 接收一组参数，一组匹配的域名列表，这个模板是一个 ant 分隔的模板，用.号作为分隔符。   它通过参数中的主机地址作为匹配规则
            #- Query=username, \d+  # 要有参数名username并且值还要是整数才能路由
            #- RemoteAddr=192.168.124.1/24 # 外部访问我的IP限制，最大跨度不超过32，目前是1~24它们是 CIDR 表示法。
            #- Method=GET,POST #配置某个请求地址，只能用Get/Post方法访问，方法限制




        - id: pay_routh2 #pay_routh2                #路由的ID(类似mysql主键ID)，没有固定规则但要求唯一，建议配合服务名
          #uri: http://localhost:8001                #匹配后提供服务的路由地址
          uri: lb://cloud-payment-service                #匹配后提供服务的路由地址
          predicates:
            - Path=/pay/gateway/info/**              # 断言，路径相匹配的进行路由
